# Generated by Django 5.1.3 on 2024-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="country",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("Not Specified", "Not Specified"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="langauge",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="state",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
